
// This file was auto-generated by ML.NET Model Builder. 

using MLModelMachineGym_4;
using System.IO;

// Create single instance of sample data from first line of dataset for model input
var imageBytes = File.ReadAllBytes(@"C:\Users\David\Desktop\David\Erasmus\FinalProject\MainWeb\MainWeb\wwwroot\data\bench_press\00000001.jpg");
MLModelMachineGym.ModelInput sampleData = new MLModelMachineGym.ModelInput()
{
    ImageSource = imageBytes,
};

// Make a single prediction on the sample data and print results.
var sortedScoresWithLabel = MLModelMachineGym.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}
